### ISSUE TITLE
[Feature Request] Effect expiration when token defeated!

### ISSUE THREAD

**Issue by thatlonelybugbear** [krbz999/effectmacro#10]
Either that or when token drops to 0 hp, which might be more system specific.

**Comment by krbz999** [comment]
Since not all systems have the concept of hit points, and those that do don't all have the key in the same location, that would be downright impossible to keep system-agnostic. I'll shelve that for now.

Combatants being marked defeated I will take a look at.

**Comment by krbz999** [comment]
Trigger for combatants being marked as defeated (and script executed on the owner's client) added in the pending v10 release.
