### ISSUE TITLE
[BUG?] Uncaught (in promise) SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by thatlonelybugbear** [krbz999/effectmacro#11]
So it seems this might be a fun little bug. Commenting out the last line of the macro will trigger the error.  
In a macro for some reason I wanted to comment out the last line which should read as a plain `//}`

This will however comment out the closing `})();` of the async function wrapping of the exec!
I think you might need to space it a bit.

```js
(function anonymous(token,character,actor,scene,origin,effect
) {
(async()=>{console.log("Effect Macro args") //this is the 1st line of my macro.
/*main body of the macro*/
//if(foo===bar) { 
/*...*/
//}})();
})
```

**Comment by thatlonelybugbear** [comment]
Just realised that I didn't try without other modules to check if this is a compatibility issue. I will do that in the morning.

**Comment by krbz999** [comment]
Fixed in the pending v10 release.
