### ISSUE TITLE
[Feature Request] Variable for spell level

### ISSUE THREAD

**Issue by HavocsCall** [krbz999/effectmacro#12]
Is there a way to get the spell level that triggered the effect? This would be use for spell level scaling macros

**Comment by krbz999** [comment]
I'm not familiar with what "triggering an effect" means, and the concept of a 'spell' is not system-agnostic, so I can't consider this feature.

**Comment by HavocsCall** [comment]
Fair enough

**Comment by krbz999** [comment]
That is done easily by looking at the content of the data returned from `Item#roll()`.
