### ISSUE TITLE
[Feature Request] handle the isSuppressed property from ActiveEffect5e in some fashion

### ISSUE THREAD

**Issue by seanpg71** [krbz999/effectmacro#20]
As I can tell there currently isn't a great way to have an effect trigger when an item with an effect set to transfer to actor is equipped/attuned in 5e.

"On Effect Creation" will trigger immediately when the item is in your inventory, and "On Effect Toggle (on)" won't ever trigger as part of equipping it unless you manually toggle the effect.  Neither of those especially work with 5e's concept of 'Unavailable Effects'.

I suspect you don't want to support this since it's not system agnostic - but it'd make this way more convenient for creating magic items that do stuff when you equip/unequip them.

**Comment by krbz999** [comment]
What are you hoping to have happen?

**Comment by seanpg71** [comment]
Short version: I'd like an effect on a piece of equipment to run a macro when that equipment is properly equipped or unequipped.  Currently you can trigger when the item is put in inventory, but that doesn't account for attunement.

In this particular case, it's a magic staff with a couple spells that can use charges and an effect that increases ac - but which can also just be used as a +1 quarterstaff.  If I just make the item a quarterstaff it'll try to use the up the charges if you use it for melee attacks.  I can get around that by having two items - one for melee attacks, and one with the spells and effects and whatnot attached.  But it's nice to just have one item, so made it a trinket and added a macro that creates/destroys an extra +1 quarterstaff item on the sheet and attached it to the effect that grants AC bonuses and whatever else the item does.  It works great - but doesn't quite work exactly correctly.

If I toggle attunement or equip/unequip the staff, the ac bonus bit of the effect turns on and off as expected because the 5e system handles that.  But as far as effect macro is concerned - the effect is just on the whole time.  It would be nice if it triggered the "On Effect Toggle (on)" and "On Effect Toggle (off)" macro when an effect switched from unavailable to active because the item was attuned.

Is not a huge deal and my use case is needlessly complicated and silly.  But it would be a handy feature to have - would make it simpler to make magic items that do arbitrary things when attuned.  Pretty sure I could do what I want with some combination of DAE and ItemMacro but I like how much cleaner Effect Macro is. 🤷‍♀️

**Comment by krbz999** [comment]
Would it be sufficient if 'toggle off' and 'toggle on' were triggered when an effect became suppressed or unsuppressed?
I'll have a look and see if that's doable.

**Comment by seanpg71** [comment]
That would be great!
