### ISSUE TITLE
Feature Request: Ability to share macros between effect conditions.

### ISSUE THREAD

**Issue by tposney** [krbz999/effectmacro#27]
Particularly with the new toggle on/off and create/delete effect it would be nice to be able to share a macro between the  various triggering conditions.

Toggle an effect off and deleting the effect will often end up being equivalent macro calls.

**Comment by krbz999** [comment]
They aren't new.

Could you clarify the difference between what you were hoping for and what a simple `effect.callMacro("onDelete")` would do?

**Comment by tposney** [comment]
I didn't think of that :(
