### ISSUE TITLE
Manipulating an effect before it is applied

### ISSUE THREAD

**Issue by DFreds** [krbz999/effectmacro#30]
Is there a way to change the active effect data before it is applied to an actor? For instance, I want to add some `changes` to the active effect based on certain conditions on the actor, but it doesn't seem to be working.

**Comment by krbz999** [comment]
You would need to use the core `preCreateActiveEffect` hook. EM simply calls embedded scripts after creation.

**Comment by DFreds** [comment]
Yeah, makes sense. Thanks!
