### ISSUE TITLE
Request: (dnd5e) Make the macro in an item's effect specific to that items usage

### ISSUE THREAD

**Issue by YenBenGrey** [krbz999/effectmacro#33]
Request - When you add macros to an item’s EM, those macros only trigger when an actor uses that specific item. 
In an effect of an item, there are other options other than transfer to actor such as effect the actor when item is rolled. Could they work? 
Or possibly invent a whole new macro module where a macro is triggered from an action. 
Action Macro 😎

**Comment by krbz999** [comment]
I am not seeing this option you are refering to.

![image](https://user-images.githubusercontent.com/50169243/217200772-9a771cf5-dcc7-4003-b403-d320c34bb3b0.png)

You can just do `if(this.item !== origin) return;`.

**Comment by YenBenGrey** [comment]
Must be another module giving those options. 

Where’s your EM options in the screenshot?

**Comment by krbz999** [comment]
Not currently enabled in the screenshot. It only provides the dropdown of triggers.

**Comment by krbz999** [comment]
This is a fun idea for a different module, sure, but sadly out of scope for EM.
