### ISSUE TITLE
This module MIGHT be causing WebGL crashes

### ISSUE THREAD

**Issue by GambetTV** [krbz999/effectmacro#39]
I've been having a very strange issue as of late. I'll be editing an item in a DnD5e character sheet, and modifying how much damage an attack does, or the range of a weapon or something like that, and my Foundry App will flash black, and the background map of my scene will vanish, leaving just the tokens, light sources, and sometimes tiles behind. This is a fairly recent development, within the last week or two, and is VERY DIFFICULT to duplicate. It doesn't happen often, but for instance if I craft a new NPC and give them say, 8 features/abilities, I'll probably get 0-2 instances of this WebGL crash. My console mentions WebGL context crash or something to that effect.

I've been troubleshooting it for a while, fully reinstalling my GPU drivers, Foundry, etc. Nothing seems to have worked. I spent the day making a dozen random NPCs just to test things out while using "Find the Culprit" to see if it might be a module causing it, and it *seems* like it might be yours. I'd put my degree of confidence at like 30%. With only a few modules enabled, plus yours, the crash would occur. When I've disabled yours, but left my other 90 active, I haven't had an issue. But because of how random it is I don't know if that's because your module is the problem or if it just hasn't crashed in a few hours.

Anyway, I just figured I'd post this to see if you could think of any reason why your last update or two might have caused this, or if that just seems impossible to you, while I attempt to figure this all out. Thanks in advance for looking into it for me!

**Comment by krbz999** [comment]
> or if that just seems impossible to you

One hundred percent.

**Comment by thatlonelybugbear** [comment]
@GambetTV  What's your Foundry version and which macro editor do you use (if not the core one)?

**Comment by krbz999** [comment]
Appreciate if you take this to a discord troubleshooting channel. It isn't relevant to this module.
