### ISSUE TITLE
[Question] Setting up Effect Macro through script

### ISSUE THREAD

**Issue by MastaGooz** [krbz999/effectmacro#40]
Hi !

I use macros like that to apply effects on tokens : 

// Apply an active effect to every selected token
// This effect will trigger any effect modifiers as long as the ID matches the actual effect ID in the system
let selected = canvas.tokens.controlled;
if (selected.length === 0) ui.notifications.warn("Select at least one token !");
else {
    selected.forEach(token => {
        let effectData = {
            name: "Dead", // Actual name of the effect (can be changed as long as the ID is the right one)
            icon: "icons/svg/skull.svg", // Icon of the effect (can be changed as long as the ID is the right one)
            duration: { seconds: 60 }, // Duration of the effect in second
            origin: token.document.uuid, // ID of the source (selected token in exemple)
            sourceName: "effect source", // Name of the source
            disabled: false, // Is the effect active or not
            description: "This does that...", // Description of the effect
            flags: { core: { statusId: "dead" } } // The actual ID of the active effect (IMPORTANT !)
        };
        token.actor.createEmbeddedDocuments("ActiveEffect", [effectData]);
    });
}

Is it possible to set the effect macro like that also ?

**Comment by krbz999** [comment]
I recommend joining the discord for questions about module usage such as these. However, the answer is yes; you can as always inspect a created (and `toObject`d) effect and see its data structure, and you'd see the flags embedded by this module.
