### ISSUE TITLE
Questions about Macros

### ISSUE THREAD

**Issue by pedroaugustobt** [krbz999/effectmacro#54]
Questions

I'm starting to use the module now to test some automated functions per turn, but my code that I use doesn't work when I add it to the Effect Macro.

Macro:
```actor = arguments[1];
const damage = 2;
const currentHP = actor.system.derivedStats.hp.value;
const newHP = currentHP - damage;
await actor.update({ 'system.derivedStats.hp.value': newHP });
```
This macro worked well, but it was manual, in Effect Macro this error occurs:
foundry.js:71220 Error: You must provide an _id for every object in the update data Array.

**Comment by krbz999** [comment]
Please provide the full error stack.

**Comment by pedroaugustobt** [comment]
```
Error: You must provide an _id for every object in the update data Array.
    at #preUpdateDocumentArray (foundry-esm.js:55735:34)
    at ClientDatabaseBackend._updateDocuments (foundry-esm.js:55701:58)
    at ClientDatabaseBackend.update (foundry-esm.js:12255:19)
    at async ActiveEffect.updateDocuments (foundry-esm.js:11392:23)
    at async ActiveEffect.update (foundry-esm.js:11502:23)
    at async #onSubmitDocumentForm (foundry-esm.js:45677:7)
    at async EffectMacroConfig._onSubmitForm (foundry-esm.js:45077:11)
fetch @ foundry.js:71220
notify @ foundry.js:71116
error @ foundry.js:71153
_onSubmitForm @ foundry-esm.js:45079
```

**Comment by pedroaugustobt** [comment]
Maybe I'm doing it wrong, this is my first time using the module, do you have a code model that you can give me so I can see the pattern?

**Comment by krbz999** [comment]
This doesn't entirely look like it is an issue with the module. Please join the discord for further troubleshooting.

**Comment by krbz999** [comment]
Turned out to be an issue with CUB.
