### ISSUE TITLE
Effect Config dropdown does not remember last selected option

### ISSUE THREAD

**Issue by DOMtheDM** [krbz999/effectmacro#6]
Foundry V9 Build 269
Browser Chrome

Absolutely love what I can do with this module, but whenever I update the Effect Macro choice in the drop down menu and click Submit Changes, the next time I go to edit the effect it defaults back to "Never Automatically" again.

**Comment by krbz999** [comment]
To clarify, the macros save correctly yeah? But the selected option in the dropdown defaults to Never when the config is re-rendered

**Comment by DOMtheDM** [comment]
> To clarify, the macros save correctly yeah? But the selected option in the dropdown defaults to Never when the config is re-rendered

That's correct. I noticed sometimes the macro wouldn't save as well but I had a hard time reproducing it consistently. Once I got the macro to save however, I never had that issue again. Just the Effect Config resets. 

> Foundry V9 Build 269 Browser Chrome
> 
> Absolutely love what I can do with this module, but whenever I update the Effect Macro choice in the drop down menu and click Submit Changes, the next time I go to edit the effect it defaults back to "Never Automatically" again.

**Comment by DOMtheDM** [comment]
> To clarify, the macros save correctly yeah? But the selected option in the dropdown defaults to Never when the config is re-rendered

That's correct. I noticed sometimes the macro wouldn't save as well but I had a hard time reproducing it consistently. Once I got the macro to save however, I never had that issue again. Just the Effect Config resets.

**Comment by thatlonelybugbear** [comment]
Just so as not to open a new issue as it seems to be similar in nature (let me know if you want a separate one).

I think there should be an indication that an effect has an Effect Macro already. Maybe change the default option shown in the dropdown menu, to be one that has at least a macro.

**Comment by krbz999** [comment]
The effect config remembers the last updated macro as of v1.0.1 and will default to that option in the dropdown select.
