### ISSUE TITLE
Suggestion: Show all applied macros

### ISSUE THREAD

**Issue by HavocsCall** [krbz999/effectmacro#7]
Current setup: You need to click through all options to see which ones actually have a macro assigned and to modify them.

Suggestion: When a macro is applied, can it create a new dropdown to add another action/macro below it or something to make it more clear which actions have macros applied.

So it would look something like:

On Effect Creation (Check)
On Effect Deletion (Check)
New action here if needed

Or even just have all of them listed with checks or arrows

**Comment by krbz999** [comment]
Can you clarify what you mean by 'new dropdown'.

I can look into prepending the `select` options with a checkmark or similar, however you can simply click the `select` twice and use the up and down arrow keys to quick browse through them.

**Comment by HavocsCall** [comment]
When you save changes to the first action/macro, it makes a new dropdown to continuing adding more, while keeping the first one showing. My wonderful photo editing skills will clear it right up with no confusion whatsoever...right?
![Screenshot 2022-07-20 162605](https://user-images.githubusercontent.com/49051014/180076342-0e19104a-3691-4b78-9e65-7d73485c5a05.png)
 So in this one image, I can see that it has a macro attached to creation and a macro attached to deletion. Ideally, there would be a "new action" button or dropdown to add to it further.

**Comment by krbz999** [comment]
I am going to be looking into a way to solve this with a new interface that does not become more unwieldy the more options are added as triggers to the module.
While I don't know what the solution is going to be yet, I am keeping this issue open as a reminder. Thank you. :)

**Comment by krbz999** [comment]
The v10 version does not get rid of the dropdown but does improve upon it, clearly marking which options have macros embedded, as well as sorting them.
